// <auto-generated />
using System;
using AvtoNetScraper.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AvtoNetScraper.Migrations
{
    [DbContext(typeof(CarsContext))]
    [Migration("20200515091445_AddedUnfinishedCar")]
    partial class AddedUnfinishedCar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("AvtoNetScraper.Database.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UrlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrlId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("AvtoNetScraper.Database.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("AvtoNetScraper.Database.Car", b =>
                {
                    b.HasOne("AvtoNetScraper.Database.Url", "Url")
                        .WithMany()
                        .HasForeignKey("UrlId");
                });
#pragma warning restore 612, 618
        }
    }
}
